name: Python Linting

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.1' 

    - name: Install Ruff
      run: pip install ruff

    - name: Run Ruff Lint
      run: ruff .
